### ISSUE TITLE
Panic in overlay network peerdb.peerDbAdd 

### ISSUE THREAD

**Issue by varokas** [docker/libnetwork#1344]
We were experimenting with overlay networking in Docker version 1.11.2, running on about 10 VMs on the same network. The workload involves creating and deleting overlay network multiple times (about 3 times an hour) with 40 nodes joining in a network at a time. 

One in a while (about once a day) docker-engine in one of the VMs will panic with this in /var/log/messages. 

```
docker: panic: sync: WaitGroup is reused before previous Wait has returned
docker: goroutine 4949 [running]:
docker: sync.(*WaitGroup).Wait(0x2219190)
docker: /usr/local/go/src/sync/waitgroup.go:128 +0x114
docker: github.com/docker/libnetwork/drivers/overlay.(*driver).peerDbAdd(0xc820132e60, 0xc8236c7d00, 0x40, 0xc8236c7d40, 0x40, 0xc821b70960, 0x10, 0x10, 0xc821b7098c, 0x4, ...)
docker: /root/rpmbuild/BUILD/docker-engine/vendor/src/github.com/docker/libnetwork/drivers/overlay/peerdb.go:136 +0x32
docker: github.com/docker/libnetwork/drivers/overlay.(*driver).peerAdd(0xc820132e60, 0xc8236c7d00, 0x40, 0xc8236c7d40, 0x40, 0xc821b70960, 0x10, 0x10, 0xc821b7098c, 0x4, ...)
docker: /root/rpmbuild/BUILD/docker-engine/vendor/src/github.com/docker/libnetwork/drivers/overlay/peerdb.go:243 +0x19e
docker: github.com/docker/libnetwork/drivers/overlay.(*driver).processEvent(0xc820132e60, 0x151c, 0xc82456a960, 0x92, 0xc821fc6810, 0x2e, 0x2e, 0xc821095d01)
docker: /root/rpmbuild/BUILD/docker-engine/vendor/src/github.com/docker/libnetwork/drivers/overlay/ov_serf.go:123 +0xff5
docker: github.com/docker/libnetwork/drivers/overlay.(*driver).startSerfLoop(0xc820132e60, 0xc8217a9920, 0xc82114e120, 0xc82114e180)
docker: /root/rpmbuild/BUILD/docker-engine/vendor/src/github.com/docker/libnetwork/drivers/overlay/ov_serf.go:220 +0x4df
docker: created by github.com/docker/libnetwork/drivers/overlay.(*driver).serfInit
docker: /root/rpmbuild/BUILD/docker-engine/vendor/src/github.com/docker/libnetwork/drivers/overlay/ov_serf.go:68 +0x496
docker: goroutine 1 [chan receive, 817 minutes]:
docker: main.(*DaemonCli).CmdDaemon(0xc820405a00, 0xc82000a0d0, 0x9, 0x9, 0x0, 0x0)
docker: /root/rpmbuild/BUILD/docker-engine/docker/daemon.go:337 +0x23e1
docker: reflect.callMethod(0xc8203f1c20, 0xc821a69c78)
docker: /usr/local/go/src/reflect/value.go:628 +0x1fc
docker: reflect.methodValueCall(0xc82000a0d0, 0x9, 0x9, 0x1, 0xc8203f1c20, 0x0, 0x0, 0xc8203f1c20, 0x0, 0x47ccb4, ...)
docker: /usr/local/go/src/reflect/asm_amd64.s:29 +0x36
docker: github.com/docker/docker/cli.(*Cli).Run(0xc8203f1b00, 0xc82000a0c0, 0xa, 0xa, 0x0, 0x0)
docker: /root/rpmbuild/BUILD/docker-engine/.gopath/src/github.com/docker/docker/cli/cli.go:89 +0x383
docker: main.main()
```

**Comment by aboch** [comment]
Thanks @varokas for reporting this.
