### ISSUE TITLE
too many libnetwork-setkey process suspending, create new container timeout due to possible dead lock 

### ISSUE THREAD

**Issue by yowenter** [docker/libnetwork#2208]
![wechatimg51](https://user-images.githubusercontent.com/6657718/41921172-dd6a8d1e-7994-11e8-894c-3ac0c1efe4ab.jpeg)
![2018-06-26 16 12 08](https://user-images.githubusercontent.com/6657718/41921227-f8f55294-7994-11e8-9f69-c6f9414f52ea.png)

<img width="1271" alt="2018-06-26 11 55 08" src="https://user-images.githubusercontent.com/6657718/41921383-55153300-7995-11e8-951c-fdbedb8a89ef.png">

Hi, there :-) 

I found there are thousands of "libnetwork-setkey" processes suspending state on my machine.
The strace the processs shows it's waitting for "futex". 
As I use docker debug mode, I found the root cause maybe related to 

[service_linux.go connectedLoadbalancers ](https://github.com/docker/libnetwork/blob/bump_17.09/service_linux.go#L46)

docker debug  goroutine stacks:

goroutine 378021253 [semacquire, 362 minutes]:
sync.runtime_SemacquireMutex(0xc43b07b2f0)
	/usr/local/go/src/runtime/sema.go:62 +0x34
sync.(*Mutex).Lock(0xc43b07b2ec)
	/usr/local/go/src/sync/mutex.go:87 +0x9d
github.com/docker/docker/vendor/github.com/docker/libnetwork.(*network).connectedLoadbalancers(0xc46751f860, 0xc42911acc0, 0xc45a5299a0, 0x7f522c6dee70)
	/root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/service_linux.go:46 +0x272
github.com/docker/docker/vendor/github.com/docker/libnetwork.(*sandbox).populateLoadbalancers(0xc42bc8fe00, 0xc47128ab00)
	/root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/service_linux.go:98 +0x107
github.com/docker/docker/vendor/github.com/docker/libnetwork.(*sandbox).populateNetworkResources(0xc42bc8fe00, 0xc47128ab00, 0x2, 0x2)
	/root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/sandbox.go:865 +0x2b7
github.com/docker/docker/vendor/github.com/docker/libnetwork.(*sandbox).SetKey(0xc42bc8fe00, 0xc436cbec20, 0x12, 0x0, 0x0)
	/root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/sandbox.go:670 +0x23f
github.com/docker/docker/vendor/github.com/docker/libnetwork.(*controller).processExternalKey(0xc420518900, 0x2763300, 0xc4314ba488, 0x0, 0x437558)
	/root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/sandbox_externalkey_unix.go:171 +0x1bf
github.com/docker/docker/vendor/github.com/docker/libnetwork.(*controller).acceptClientConnections.func1(0x2763300, 0xc4314ba488, 0xc420518900)
	/root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/sandbox_externalkey_unix.go:139 +0x71
created by github.com/docker/docker/vendor/github.com/docker/libnetwork.(*controller).acceptClientConnections
	/root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/sandbox_externalkey_unix.go:149 +0x8d

docker info:

Containers: 32
 Running: 18
 Paused: 0
 Stopped: 14
Images: 153
Server Version: 17.09.1-ce
Storage Driver: overlay
 Backing Filesystem: extfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: uu84o7h0cquhgpr3d0lvuum00
 Is Manager: true
 ClusterID: ud4r18wwd26rgu474g2upalfv
 Managers: 3
 Nodes: 17
 Orchestration:
  Task History Retention Limit: 1
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Autolock Managers: false
 Root Rotation In Progress: false
 Node Address: 10.133.96.9
 Manager Addresses:
  10.133.96.10:2377
  10.133.96.8:2377
  10.133.96.9:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-693.21.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 32
Total Memory: 125.6GiB
Name: service-prd96-9
ID: GB6Q:2EQU:NKBD:3IYB:XBAA:N24V:FEKL:XCBL:K4IU:AWDM:323C:I2GG
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 1401
 Goroutines: 3640
 System Time: 2018-06-26T10:34:34.156542387+08:00
 EventsListeners: 16
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 0.0.0.0/0
 127.0.0.0/8
Live Restore Enabled: false

**Comment by fcrisciani** [comment]
@yowenter thanks definitely for the analysis that is helpful, the only problem is that you are using a very dated version of the engine... are you able to reproduce the same issue with the latest stable: 18.03.1-ce?

**Comment by fcrisciani** [comment]
@yowenter my best guess on the base of this info is that is related to this: https://github.com/vishvananda/netlink/pull/280
Basically what can happen is that the netlink socket gets closed but the recv does not unblock and will hold the service lock indefinitely.

**Comment by yowenter** [comment]
`	for _, s := range serviceBindings {
		s.Lock()
		// Skip the serviceBindings that got deleted
		if s.deleted {
			s.Unlock()
			continue
		}
		if lb, ok := s.loadBalancers[n.ID()]; ok {
			lbs = append(lbs, lb)
		}
		s.Unlock()
	}`

@fcrisciani 
Sorry, I don't know much about netlink . 
It seems that there's no network request  in  the code after acquire the lock. 
So.. I can't figure out why the dead lock happens, could you please explain more in details?

**Comment by fcrisciani** [comment]
@yowenter that one is only the go routine that is stuck on the lock, but the interesting one will be the actual go routine that is holding the mutex. You can send the SIGUSR1 to the daemon to dump the go routines and try to figure it out which is the one holding the lock.

My comment is about one specific bug in the kernel that do not release a Receive if the netlink socket is closed. That in the past (you are using an old version of the engine 17.09-ce that I confirmed do not have the fix), was causing sometime that kind of deadlock where during the configuration of the load balancer the service lock is taken and the netlink is used to configure the IPVS rules towards the kernel. Now if the kernel bug is hit, the routine that tries to configure the IPVS rules holding the lock was remaining stuck on the receive (https://github.com/docker/docker-ce/blob/afdb6d44a80f777069885a9ee0e0f86cf841b1bb/components/engine/vendor/github.com/docker/libnetwork/ipvs/netlink.go#L223)
At that point the mutex for that service will be hold forever and so all next tasks on that node that will be scheduled will remain block on the lock acquisition

**Comment by yowenter** [comment]
```
goroutine 114727591 [syscall, 26344 minutes]:
syscall.Syscall6(0x2d, 0x118, 0xc432a26000, 0x1000, 0x0, 0xc430a69c28, 0xc430a69c1c, 0x2b, 0x7f5294273d88, 0x4590b0)
	/usr/local/go/src/syscall/asm_linux_amd64.s:44 +0x5
syscall.recvfrom(0x118, 0xc432a26000, 0x1000, 0x1000, 0x0, 0xc430a69c28, 0xc430a69c1c, 0x0, 0x1, 0xc4488f8800)
	/usr/local/go/src/syscall/zsyscall_linux_amd64.go:1712 +0x99
syscall.Recvfrom(0x118, 0xc432a26000, 0x1000, 0x1000, 0x0, 0x1000, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/syscall/syscall_unix.go:252 +0xaf
github.com/docker/docker/vendor/github.com/vishvananda/netlink/nl.(*NetlinkSocket).Receive(0xc4414648a0, 0xc454aa43f0, 0x1, 0x1, 0x0, 0x0)
	/root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/vendor/github.com/vishvananda/netlink/nl/nl_linux.go:613 +0x9b
github.com/docker/docker/vendor/github.com/docker/libnetwork/drivers/overlay.(*network).watchMiss(0xc420175b80, 0xc4414648a0)
	/root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/drivers/overlay/ov_network.go:715 +0x6c
created by github.com/docker/docker/vendor/github.com/docker/libnetwork/drivers/overlay.(*network).initSandbox
	/root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/drivers/overlay/ov_network.go:703 +0x581
```
I found there is a goroutine  stack related to netlink.

**Comment by yowenter** [comment]
https://github.com/vishvananda/netlink/issues/254

**Comment by yowenter** [comment]
https://github.com/vishvananda/netlink/pull/170

**Comment by ctelfer** [comment]
Yep, I think that is the condition that @fcrisciani was referring to.

**Comment by yowenter** [comment]
@fcrisciani  Thanks much !
