### ISSUE TITLE
Extremely slow container startup related to libnetwork

### ISSUE THREAD

**Issue by vania-pooh** [docker/libnetwork#2284]
Having recent Docker version...
```
root@my-host:~# docker version
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:24:51 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:23:15 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```

... recent Ubuntu...

```
root@my-host:~# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic
```

... recent kernel ...

```
root@my-host:~# uname -a
Linux my-host 4.15.0-33-generic #36-Ubuntu SMP Wed Aug 15 16:00:05 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

Docker is configured to work in IPv6-only environment...
```
# sysctl net.ipv6.conf.eth0.accept_ra=2
# ip6tables -t nat -A POSTROUTING -s 2001:db8:0:2::/64 ! -o docker0 -j MASQUERADE
# sysctl net.ipv6.conf.default.forwarding=1
# sysctl net.ipv6.conf.all.forwarding=1
```
... and daemon is started with additional flags:
```
--bridge=docker0 --ipv6 --fixed-cidr-v6=2001:db8:0:2::/64 --dns <dns-server-ipv6-address>
```

Our application is frequently starting and stopping up to 50 containers in parallel and under the load containers are beginning to start very slowly. Usually it takes seconds to do `docker create` and `docker start` but when this issue is reproducing `docker create` is still fast, but `docker start` takes minutes to finish. All containers are started in `default` bridge network (no custom networks are used). Tried even with standard Ubuntu images and `docker run` command took 2 minutes to complete:
```
93b548df2c7b        ubuntu:16.04                             "bash"                   2 minutes ago       Up 2 seconds                                 pedantic_feynman
```
Dumped all `dockerd` goroutines:
[docker_goroutines.log](https://github.com/docker/libnetwork/files/2534181/docker_goroutines.log)

Seeing a lot of goroutines like this:
```
Oct 31 13:37:58 localhost dockerd[24601]: goroutine 71217 [semacquire]:
Oct 31 13:37:58 localhost dockerd[24601]: sync.runtime_SemacquireMutex(0xc421ada454, 0x0)
Oct 31 13:37:58 localhost dockerd[24601]:         /usr/local/go/src/runtime/sema.go:71 +0x3f
Oct 31 13:37:58 localhost dockerd[24601]: sync.(*Mutex).Lock(0xc421ada450)
Oct 31 13:37:58 localhost dockerd[24601]:         /usr/local/go/src/sync/mutex.go:134 +0x10a
Oct 31 13:37:58 localhost dockerd[24601]: github.com/docker/docker/pkg/locker.(*lockCtr).Lock(0xc421ada450)
Oct 31 13:37:58 localhost dockerd[24601]:         /go/src/github.com/docker/docker/pkg/locker/locker.go:56 +0x2f
Oct 31 13:37:58 localhost dockerd[24601]: github.com/docker/docker/pkg/locker.(*Locker).Lock(0xc420e6c3d0, 0xc420696d00, 0x40)
Oct 31 13:37:58 localhost dockerd[24601]:         /go/src/github.com/docker/docker/pkg/locker/locker.go:91 +0xb2
Oct 31 13:37:58 localhost dockerd[24601]: github.com/docker/docker/vendor/github.com/docker/libnetwork.(*network).CreateEndpoint(0xc421516380, 0xc42111a441, 0xd, 0xc4200d1400, 0x5, 0x8, 0x0, 0x0, 0x0, 0x0)
Oct 31 13:37:58 localhost dockerd[24601]:         /go/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/network.go:1150 +0xf3
Oct 31 13:37:58 localhost dockerd[24601]: github.com/docker/docker/daemon.(*Daemon).connectToNetwork(0xc420448540, 0xc4203ff440, 0x56509d520111, 0x6, 0xc42176e540, 0x600, 0x0, 0x0)
Oct 31 13:37:58 localhost dockerd[24601]:         /go/src/github.com/docker/docker/daemon/container_operations.go:749 +0x36b
Oct 31 13:37:58 localhost dockerd[24601]: github.com/docker/docker/daemon.(*Daemon).allocateNetwork(0xc420448540, 0xc4203ff440, 0x0, 0x0)
Oct 31 13:37:58 localhost dockerd[24601]:         /go/src/github.com/docker/docker/daemon/container_operations.go:540 +0xa31
Oct 31 13:37:58 localhost dockerd[24601]: github.com/docker/docker/daemon.(*Daemon).initializeNetworking(0xc420448540, 0xc4203ff440, 0x0, 0x0)
Oct 31 13:37:58 localhost dockerd[24601]:         /go/src/github.com/docker/docker/daemon/container_operations.go:953 +0xa2
Oct 31 13:37:58 localhost dockerd[24601]: github.com/docker/docker/daemon.(*Daemon).containerStart(0xc420448540, 0xc4203ff440, 0x0, 0x0, 0x0, 0x0, 0x1, 0x0, 0x0)
Oct 31 13:37:58 localhost dockerd[24601]:         /go/src/github.com/docker/docker/daemon/start.go:150 +0x2c2
Oct 31 13:37:58 localhost dockerd[24601]: github.com/docker/docker/daemon.(*Daemon).ContainerStart(0xc420448540, 0xc422cf7c87, 0x40, 0x0, 0x0, 0x0, 0x0, 0x0, 0x56509dd58a20, 0xc421e5b601)
Oct 31 13:37:58 localhost dockerd[24601]:         /go/src/github.com/docker/docker/daemon/start.go:95 +0x1c4
Oct 31 13:37:58 localhost dockerd[24601]: github.com/docker/docker/api/server/router/container.(*containerRouter).postContainersStart(0xc420f765c0, 0x56509e1692a0, 0xc422520a80, 0x56509e167760, 0xc420bdb340, 0xc422e4ef00, 0xc422520990, 0x56509d51eb47, 0x5)
Oct 31 13:37:58 localhost dockerd[24601]:         /go/src/github.com/docker/docker/api/server/router/container/container_routes.go:203 +0x26a
Oct 31 13:37:58 localhost dockerd[24601]: github.com/docker/docker/api/server/router/container.(*containerRouter).(github.com/docker/docker/api/server/router/container.postContainersStart)-fm(0x56509e1692a0, 0xc422520a80, 0x56509e167760, 0xc420bdb340, 0xc422e4ef00, 0xc422
520990, 0x56509c0c199c, 0x56509dfaefe0)
Oct 31 13:37:58 localhost dockerd[24601]:         /go/src/github.com/docker/docker/api/server/router/container/container.go:52 +0x6b
Oct 31 13:37:58 localhost dockerd[24601]: github.com/docker/docker/api/server/middleware.ExperimentalMiddleware.WrapHandler.func1(0x56509e1692a0, 0xc422520a80, 0x56509e167760, 0xc420bdb340, 0xc422e4ef00, 0xc422520990, 0x56509e1692a0, 0xc422520a80)
Oct 31 13:37:58 localhost dockerd[24601]:         /go/src/github.com/docker/docker/api/server/middleware/experimental.go:26 +0xda
Oct 31 13:37:58 localhost dockerd[24601]: github.com/docker/docker/api/server/middleware.VersionMiddleware.WrapHandler.func1(0x56509e1692a0, 0xc4225209f0, 0x56509e167760, 0xc420bdb340, 0xc422e4ef00, 0xc422520990, 0x18, 0xc421e5b8f8)
Oct 31 13:37:58 localhost dockerd[24601]:         /go/src/github.com/docker/docker/api/server/middleware/version.go:62 +0x401
Oct 31 13:37:58 localhost dockerd[24601]: github.com/docker/docker/pkg/authorization.(*Middleware).WrapHandler.func1(0x56509e1692a0, 0xc4225209f0, 0x56509e167760, 0xc420bdb340, 0xc422e4ef00, 0xc422520990, 0x56509bfad867, 0x56509d6e71b8)
Oct 31 13:37:58 localhost dockerd[24601]:         /go/src/github.com/docker/docker/pkg/authorization/middleware.go:59 +0x7ab
Oct 31 13:37:58 localhost dockerd[24601]: github.com/docker/docker/api/server/middleware.DebugRequestMiddleware.func1(0x56509e1692a0, 0xc4225209f0, 0x56509e167760, 0xc420bdb340, 0xc422e4ef00, 0xc422520990, 0x56509e1692a0, 0xc4225209f0)
Oct 31 13:37:58 localhost dockerd[24601]:         /go/src/github.com/docker/docker/api/server/middleware/debug.go:25 +0x8db
Oct 31 13:37:58 localhost dockerd[24601]: github.com/docker/docker/api/server.(*Server).makeHTTPHandler.func1(0x56509e167760, 0xc420bdb340, 0xc422e4ef00)
Oct 31 13:37:58 localhost dockerd[24601]:         /go/src/github.com/docker/docker/api/server/server.go:141 +0x19a
Oct 31 13:37:58 localhost dockerd[24601]: net/http.HandlerFunc.ServeHTTP(0xc4205a85a0, 0x56509e167760, 0xc420bdb340, 0xc422e4ef00)
Oct 31 13:37:58 localhost dockerd[24601]:         /usr/local/go/src/net/http/server.go:1947 +0x46
Oct 31 13:37:58 localhost dockerd[24601]: github.com/docker/docker/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc420a0cd20, 0x56509e167760, 0xc420bdb340, 0xc422e4ef00)
Oct 31 13:37:58 localhost dockerd[24601]:         /go/src/github.com/docker/docker/vendor/github.com/gorilla/mux/mux.go:103 +0x228
Oct 31 13:37:58 localhost dockerd[24601]: github.com/docker/docker/api/server.(*routerSwapper).ServeHTTP(0xc420f29ed0, 0x56509e167760, 0xc420bdb340, 0xc422e4ef00)
Oct 31 13:37:58 localhost dockerd[24601]:         /go/src/github.com/docker/docker/api/server/router_swapper.go:29 +0x72
Oct 31 13:37:58 localhost dockerd[24601]: net/http.serverHandler.ServeHTTP(0xc42001f110, 0x56509e167760, 0xc420bdb340, 0xc422e4ef00)
Oct 31 13:37:58 localhost dockerd[24601]:         /usr/local/go/src/net/http/server.go:2694 +0xbe
Oct 31 13:37:58 localhost dockerd[24601]: net/http.(*conn).serve(0xc4219ed860, 0x56509e1691e0, 0xc4202c9b80)
Oct 31 13:37:58 localhost dockerd[24601]:         /usr/local/go/src/net/http/server.go:1830 +0x653
Oct 31 13:37:58 localhost dockerd[24601]: created by net/http.(*Server).Serve
Oct 31 13:37:58 localhost dockerd[24601]:         /usr/local/go/src/net/http/server.go:2795 +0x27d
```
It seems that for some reason network initialization is waiting for a lock.

**Comment by vania-pooh** [comment]
Any comments on this?

**Comment by vania-pooh** [comment]
Initially everything was running in default Docker network. Tried the same thing with custom Docker networks - no difference. For slowly starting containers doing `docker inspect` also freezes until container starts.

**Comment by vania-pooh** [comment]
Seems to be caused by hard disk performance. Migrating to SSD seems to fix the problem.
