### ISSUE TITLE
creating multiple bridge networks concurrently fails

### ISSUE THREAD

**Issue by campbellr** [docker/libnetwork#915]
I have some tests that spins up containers in a bridged network, but when i run tests in parallel i end up getting failures like this:

```
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "docker_test.py", line 11, in create_network
    n = c.create_network(name)
  File "/localhome/campbr9/.local/lib/python3.4/site-packages/docker/utils/decorators.py", line 35, in wrapper
    return f(self, *args, **kwargs)
  File "/localhome/campbr9/.local/lib/python3.4/site-packages/docker/api/network.py", line 29, in create_network
    return self._result(res, json=True)
  File "/localhome/campbr9/.local/lib/python3.4/site-packages/docker/client.py", line 146, in _result
    self._raise_for_status(response)
  File "/localhome/campbr9/.local/lib/python3.4/site-packages/docker/client.py", line 142, in _raise_for_status
    raise errors.APIError(e, response, explanation=explanation)
docker.errors.APIError: 409 Client Error: Conflict ("b'cannot create network br-2912151829a5 (0548ba54b35ce9b10e4fedeab3b081bb845d019372533c9f16b88377bf2e713c): conflicts with network 2912151829a51ab8b4c68a13474f427ae28d1983b36a1a0d18c2acbf60221334 (br-2912151829a5): networks have overlapping IPv4'")
```

(I've filed #914 to cover the fact that the error message implies that both networks have the same bridge name, which isn't really the case)

It seems like something in the network creation isn't properly serialized, although I'm not familiar enough with the code to tell where the problem is.

This is my docker version:

```
$ docker --version
Docker version 1.9.1, build a34a1d5
```

And the trivial test I wrote to reproduce:

```python
from uuid import uuid4
from threading import Thread
from docker import Client

c = Client()


def create_network():
    name = uuid4().hex  # just making sure the name is unique
    n = c.create_network(name)
    c.remove_network(n['Id'])


if __name__ == '__main__':
    threads = []

    for i in range(10):
        t = Thread(target=create_network)
        t.start()
        threads.append(t)

    for t in threads:
        t.join()

```

**Comment by aboch** [comment]
@campbellr 
This seems to be the cause: `[...]  networks have overlapping IPv4`

There was a race in the code which selects the subnet to assign to the network being created. Fixed it with #890. Docker 1.10 will have the fix.

**Comment by campbellr** [comment]
Thanks @aboch. I'll try reproducing with your changes (if i can figure out how to do that...)

**Comment by aboch** [comment]
@campbellr You can download the docker 1.10-rc2 binary from [here](https://github.com/docker/docker/releases)

**Comment by campbellr** [comment]
1.10-rc2 seems to have resolved this issue. Thanks for the help (and fix)!
